services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    environment:
      - REDIS_NODES=redis-node1:6391,redis-node2:6392,redis-node3:6393

  redis-node1:
    image: redis:latest
    ports:
      - "6391:6379"
    command: redis-server --port 6379
  redis-node2:
    image: redis:latest
    ports:
      - "6392:6379"
    command: redis-server --port 6379
  redis-node3:
    image: redis:latest
    ports:
      - "6393:6379"
    command: redis-server --port 6379
