version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    environment:
      - REDIS_NODES=redis-node1:6394,redis-node2:6395,redis-node3:6396

  redis-node1:
    image: redis:latest
    ports:
      - "6394:6379"
    command: redis-server --port 6379
  redis-node2:
    image: redis:latest
    ports:
      - "6395:6379"
    command: redis-server --port 6379
  redis-node3:
    image: redis:latest
    ports:
      - "6396:6379"
    command: redis-server --port 6379
