version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    environment:
      - REDIS_NODES=redis-node1:6388,redis-node2:6389,redis-node3:6390

  redis-node1:
    image: redis:latest
    ports:
      - "6388:6379"
    command: redis-server --port 6379
  redis-node2:
    image: redis:latest
    ports:
      - "6389:6379"
    command: redis-server --port 6379
  redis-node3:
    image: redis:latest
    ports:
      - "6390:6379"
    command: redis-server --port 6379
