version: '3.8'
services:
  redis-node1:
    image: redis:latest
    container_name: redis-node1
    ports:
      - "6379:6379"
    command: redis-server --port 6379
  redis-node2:
    image: redis:latest
    container_name: redis-node2
    ports:
      - "6380:6380"
    command: redis-server --port 6380
  redis-node3:
    image: redis:latest
    container_name: redis-node3
    ports:
      - "6381:6381"
    command: redis-server --port 6381
