services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_NODES=redis-node1:6397,redis-node2:6379,redis-node3:6379
      - REDIS_HOST=redis-node1
      - REDIS_PORT=6379
    volumes:
      - .:/app
    command: python app.py

  redis-node1:
    image: redis:latest
    ports:
      - "6397:6379"
    command: redis-server --port 6379
  redis-node2:
    image: redis:latest
    ports:
      - "6398:6379"
    command: redis-server --port 6379
  redis-node3:
    image: redis:latest
    ports:
      - "6399:6379"
    command: redis-server --port 6379
