version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
    environment:
      - REDIS_NODES=redis-node1:6397,redis-node2:6398,redis-node3:6399

  redis-node1:
    image: redis:latest
    ports:
      - "6397:6379"
    command: redis-server --port 6379
  redis-node2:
    image: redis:latest
    ports:
      - "6398:6379"
    command: redis-server --port 6379
  redis-node3:
    image: redis:latest
    ports:
      - "6399:6379"
    command: redis-server --port 6379
